### ISSUE TITLE
Compilation on XSEDE

### ISSUE THREAD

**Issue by dafrost** [kuangdai/AxiSEM-3D#1]
I'm unable to compile the code on XSEDE following the instructions in the wiki. I've attached a copy of my build scripts, modules, and compilation errors.
[FrostDA_compilation_21.10.20.txt](https://github.com/kuangdai/AxiSEM-3D/files/5418214/FrostDA_compilation_21.10.20.txt)

**Comment by kuangdai** [comment]
CMake tells that

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is Intel 17.0.4.20170411

AxiSEM3D uses C++17. The minimum version is 7 for GCC and 19.0 for Intel C++.
