### ISSUE TITLE
Simulation instability (Archer) 

### ISSUE THREAD

**Issue by willeaton101** [kuangdai/AxiSEM-3D#10]
Hi Kuangdai, 

I hope you are well. I have ran a simulation with no 3D model and it worked fine. I then increased the Nr number (from 50 to 360) and included a 3D model in the simulation - it now blows up at the 2nd timestep. I assume the issue is with the 3D model input file but I cant work out what the error may be. Below are the inparam files as well as the logs from archer: 

[inparam_files.zip](https://github.com/kuangdai/AxiSEM-3D/files/5658608/inparam_files.zip)
[log.txt](https://github.com/kuangdai/AxiSEM-3D/files/5658616/log.txt)

[2hz_5_mfp_1_rad.o7520491.txt](https://github.com/kuangdai/AxiSEM-3D/files/5658621/2hz_5_mfp_1_rad.o7520491.txt)
[2hz_5_mfp_1_rad.e7520491.txt](https://github.com/kuangdai/AxiSEM-3D/files/5658623/2hz_5_mfp_1_rad.e7520491.txt)

Any advice would be amazing! I note that in inparam.source I still use half_duraction rather than half_duration as I havent updated axisem since that was corrected :)

**Comment by kuangdai** [comment]
Vp > sqrt(2) * Vs at any time as required by positiveness of elasticity tensor.

**Comment by willeaton101** [comment]
Hi, thanks for getting back to me. 

I re-ran the same simulation using new background velocities of Vp = 5800 and Vs = 3200 m/s. The same error occurred. I would have thought that, given the perturbations are 20 % positive perturbations, this would produce a Vp range of [5800, 6960] and a Vs range of [3200, 3840] - this gives a (sqrt(2)*Vs) range of [4525, 5430] such that the velocities would always satisfy this condition. Am I still making a mistake?

**Comment by kuangdai** [comment]
Try turning off both types of absorbing boundary first

**Comment by willeaton101** [comment]
It still blows up at the second timestep with both absorbing boundaries disabled (currently I am these simulations with a lower Nr value on my local computer, for reference).

**Comment by kuangdai** [comment]
Likely to be an error in the 3D file. Please post the script that generates the nc file here.

**Comment by willeaton101** [comment]
Have had t o upload as a .txt as .py files arent supported. Thanks for taking the time to look into this, I really appreciate it! 

[model_gen.txt](https://github.com/kuangdai/AxiSEM-3D/files/5659726/model_gen.txt)

**Comment by kuangdai** [comment]
The range of x and y should be -125000 to 125000

**Comment by willeaton101** [comment]
I have changed the x and y range for the 3D model. It still throws the same error with or without the absorbing boundaries active.

**Comment by kuangdai** [comment]
In your script, change the ranges to 

```python
x = np.array([-125000, 125000])
y = np.array([-125000, 125000])
z = np.array([0, 125000])
```

Then plot the model using the following code:


```python
import numpy as np
from netCDF4 import Dataset
import matplotlib.pyplot as plt

dset = Dataset('2hz_5_mfp_1_rad.nc')

vs=dset['vs'][:,:,:]

for z in range(vs.shape[-1]):
    plt.imshow(vs[:,:,z])
    plt.show()
```


I  don't think that's what you want.

**Comment by willeaton101** [comment]
Hi Kuangdai, 

I agree thats not what I want! Running the code using 

```
x = np.array([0, 125000])
y = np.array([0, 125000])
z = np.array([0, 125000])
```
gives the following which is what I am hoping for: 

![Screenshot from 2020-12-08 21-46-24](https://user-images.githubusercontent.com/43998845/101545629-73c7f680-399f-11eb-9a65-3ee4a0763c9d.png)

If the range must indeed be from -125 to 125 instead of 0 to 125 in x,y then I will need to re-write the model code accordingly. However, I am curious as to why the simulations I have previously run using the same model-generating code with 0 to 125 have all worked fine and not produced this error!

**Comment by kuangdai** [comment]
So what are the differences between your previous run and this one?

**Comment by willeaton101** [comment]
The major difference is that we set the flush to false in the inparam.output file and left the buffer at 1000. This was because the time to run the simulations got extremely large (>100 hours on a 1 Hz, 125 km^3 scale simulation on archer) for some reason but Claudia and I weren't sure why. Further, this instability initially occurred in a 1D simulation and this was resolved by reducing the courant number to 0.3 from 0.6. Given that the timing was drastically reduced by doing this, the freq. was then increased to 2 Hz.

**Comment by willeaton101** [comment]
I have also just noticed that the attenuation is set to CG4 within the inparam.model.yaml file when it was previously set to NONE but I dont know if that really would make any difference?

**Comment by kuangdai** [comment]
Maybe. Turn it off and see if it runs.

**Comment by willeaton101** [comment]
Hi Kuangdai, 

It looks like turning off the attenuation does the trick, though I'm not sure why! Thank you so much for all your help and quick replies, I really appreciate it.

**Comment by kuangdai** [comment]
So it could be a bug in attenuation. Please upload full input folder.

**Comment by willeaton101** [comment]
Here's the input folder. This just ran on my local PC with an xy domain 0 to 125 km and setting attenuation to NONE.

[input.zip](https://github.com/kuangdai/AxiSEM-3D/files/5662565/input.zip)

Thanks again for all your advice.

**Comment by kuangdai** [comment]
I changed attenuation into CG4 and FULL, both ran without instability.

**Comment by kuangdai** [comment]
This bug is fixed. Last time I could not trigger it because this bug was a compiler-specific.

Thanks.
