### ISSUE TITLE
Archer OOM error

### ISSUE THREAD

**Issue by willeaton101** [kuangdai/AxiSEM-3D#11]
Hi Kuangdai, 

Quick question from me. I increased the number of elements per wavelength from 3 to 4 for a simulation. Usually would take ~ 3 hours on 8 Archer nodes. Following this increase, Archer is showing OOM errors even using 24 nodes. I tried reducing the buffer size from 1000 to 100. Nr is currently at 360 and has been on previous simulations

Increasing the EPW seems have increased the memory requirements substantially. Does you have any recommendations for reducing the memory requirements apart from lowering the n_r value? 

Error logs attached:     

[trial_neg2.e7532249.txt](https://github.com/kuangdai/AxiSEM-3D/files/5683109/trial_neg2.e7532249.txt)
[trial_neg2.o7532249.txt](https://github.com/kuangdai/AxiSEM-3D/files/5683110/trial_neg2.o7532249.txt)
[trialneg2.txt](https://github.com/kuangdai/AxiSEM-3D/files/5683111/trialneg2.txt)

**Comment by kuangdai** [comment]
1) Instead of increasing EPW, you can increase frequency to make the mesh scale finer

2) No other way to decrease memory substantially. More resource is needed for a larger problem.
