### ISSUE TITLE
Changing DEPTH to RADIUS error 3D model

### ISSUE THREAD

**Issue by eejwa** [kuangdai/AxiSEM-3D#12]
[input.zip](https://github.com/kuangdai/AxiSEM-3D/files/5709238/input.zip)

Hi Kuangdai, 
I hope you are well. I'm doing some test runs on my laptop to get a 3D model working and I’m not sure if there’s just a typo in my input files (attached), but when I change the coordinates.vertical parameter from “DEPTH” to “RADIUS” in the 3D model section I get the error message: 

!!!!!!!!!!!! AxiSEM3D ABORTED UPON RUNTIME EXCEPTION !!!!!!!!!!! 
FROM: sg_tools::inparamVertical 
WHAT: Parameter coordinates:vertical must be either RADIUS or DEPTH. 
      Model name: Mantle_Vel_Gradient_Blob 
      Class name: StructuredGridV3D 
TIME: 2020-12-17T11:38:06 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 

I can just change my model to use depth rather than radius but just wanted to check what I was doing wrong or if there was a bug. In input.zip are the input files and the code used to make the 3D model.  

Cheers,  
Jamie

**Comment by kuangdai** [comment]
Thanks. There was a typo in the code. Fixed.
