### ISSUE TITLE
Runing issue on CSD3

### ISSUE THREAD

**Issue by Yishharu** [kuangdai/AxiSEM-3D#13]
Hi Kuangdai,

Our complied AxiSEM3D failed to run on the skylake platform (Intel Scalable processors (Intel Xeon Gold - Skylake)), it shows error:

> Please verify that both the operating system and the processor support Intel(R) AVX512ER and AVX512PF instructions.
> Please verify that both the operating system and the processor support Intel(R) AVX512ER and AVX512PF instructions.
> Please verify that both the operating system and the processor support Intel(R) AVX512ER and AVX512PF instructions.
> 
> ===================================================================================
> =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
> =   RANK 0 PID 58091 RUNNING AT cpu-e-28
> =   EXIT STATUS: 1
> ===================================================================================

when we run it on the KNL platform, (Intel Xeon Phi (KNL)), it shows the error:

> JobID: 33194091
> ======
> Time: Thu  7 Jan 12:12:41 GMT 2021
> Running on master node: knl-e-178
> Current directory: /rds/project/sc845/rds-sc845-3d-modeling/Simulation_for_Stuart
> 
> Nodes allocated:
> ================
> knl-e-178
> 
> numtasks=64, numnodes=1, mpi_tasks_per_node=64 (OMP_NUM_THREADS=1)
> 
> Executing command:
> ==================
> mpirun -np 64 -N 64 ./axisem3d > ./output/screen.txt
> 
> [mpiexec@knl-e-178] match_arg (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:59): unrecognized argument N
> [mpiexec@knl-e-178] HYD_arg_parse_array (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:74): argument matching returned error
> [mpiexec@knl-e-178] mpiexec_get_parameters (../../../../../src/pm/i_hydra/mpiexec/mpiexec_params.c:1278): error parsing input array
> [mpiexec@knl-e-178] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1653): error parsing parameters

Do you have any idea? Thanks

Zhi

**Comment by kuangdai** [comment]
Change

mpirun -np 64 -N 64 ./axisem3d > ./output/screen.txt

into

mpirun -np 64 -N 64 ./axisem3d > ./screen.txt

and rerun.  This change is due IO redesign.

If the error persists, upload screen.txt as well as files in output/develop/.

**Comment by kuangdai** [comment]
I seems a system error: -N 64 is not unrecognized.

```
[mpiexec@knl-e-178] match_arg (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:59): unrecognized argument N
```

**Comment by Yishharu** [comment]
Great, thanks Kuangdai! It works on the KNL platform now. Any idea on the 'operating system and the processor support' issue on the skylake platform?

**Comment by kuangdai** [comment]
Not sure about the problem. Please provide more details.

**Comment by Yishharu** [comment]
It's the compiling issue on different platform.  We've solved that. Many thanks!
