### ISSUE TITLE
MPI error on ARCHER2

### ISSUE THREAD

**Issue by eejwa** [kuangdai/AxiSEM-3D#14]
Hi, 

I've been trying to run AxiSEM3D on ARCHER2. It seems to compile ok when I use either the modules available on ARCHER2 or installing them via conda. The preloop seems to work fine, but code crashes with the following message once the time loop starts:

aborting job:
Fatal error in PMPI_Isend: Invalid datatype, error stack:
PMPI_Isend(160): MPI_Isend(buf=0x146474300, count=24099, MPI_DATATYPE_NULL, dest=1, tag=1, MPI_COMM_WORLD, request=0x1acc6fa0) failed
PMPI_Isend(111): Datatype for argument datatype is a null datatype
MPICH ERROR [Rank 0] [job id 96429.0] [Tue Feb  9 11:28:48 2021] [unknown] [nid001754] - Abort(738857987) (rank 0 in comm 0): Fatal error in PMPI_Isend: Invalid datatype, error stack:
PMPI_Isend(160): MPI_Isend(buf=0x135bc8cc0, count=30617, MPI_DATATYPE_NULL, dest=1, tag=1, MPI_COMM_WORLD, request=0x597d5c60) failed
PMPI_Isend(111): Datatype for argument datatype is a null datatype

The full output is in "slurm-96429.out", which is in the zip file attached. I tried changing the compiler I use from the default cray compiler to the gnu compilers using 'module restore PrgEnv-gnu' but still get the same error. Whether I use packages installed with conda or those on ARCHER2 also seems to not change anything. I'm pretty sure I'm using the latest version of the code. In the zip file attached are also my submission file and the Makefile and CMakeCache.txt file in case I have missed anything. 

Cheers,
Jamie

[archer2_error_files.zip](https://github.com/kuangdai/AxiSEM-3D/files/5972663/archer2_error_files.zip)

**Comment by mbareford** [comment]
There seems to be an issue with the compilation of "./SOLVER/src/shared/mpi/mpi.hpp" on ARCHER2, specifically the isend and irecv methods. The mapping of the Eigen type to the MPI type using "internal::typeMPI<typename EigenMat::Scalar>()" isn't working; this should resolve to "internal::typeMPI<std::complex<double>>() -> MPI_CXX_DOUBLE_COMPLEX", but that clearly isn't happening hence the MPI_DATATYPE_NULL error.

**Comment by kuangdai** [comment]
Hi Michael, thanks for pointing that out. Jamie is reporting a runtime error, which means the complier found the right typeMPI() to call. However,  for some reason MPI_CXX_DOUBLE_COMPLEX is not accepted/supported by the MPI library.

Hi Jamie, can you try to compile the code in single precision and see what's happening?

**Comment by mbareford** [comment]
I get the same error with single precision.

**Comment by eejwa** [comment]
Hi both, I also get the same error when compiling with single precision.

**Comment by mbareford** [comment]
Compiling with `internal::typeMPI<decltype(mat)::Scalar>` fails because `decltype(mat)` gives `const Eigen::Matrix<std::complex<float>, -1, 1>`, which doesn't have a Scalar member.

**Comment by kuangdai** [comment]
In an older version I was using MPI_C_DOUBLE_COMPLEX and MPI_C_FLOAT_COMPLEX and that worked well. I checked the MPI standard, MPI_CXX_DOUBLE_COMPLEX and MPI_CXX_FLOAT_COMPLEX may not be supported. 

Can you help me to test it? Maybe I should change it back.

In mpi.hpp, change MPI_CXX_DOUBLE_COMPLEX to MPI_C_DOUBLE_COMPLEX and MPI_CXX_FLOAT_COMPLEX to MPI_C_FLOAT_COMPLEX.

Thanks!

**Comment by mbareford** [comment]
I've done a few tests and `MPI_CXX_DOUBLE_COMPLEX` is recognised by the MPI libraries on ARCHER2.
Also, running `mpi::internal::typeMPI<std::complex<double>>()` works as expected: it returns `MPI_CXX_DOUBLE_COMPLEX`.

**Comment by kuangdai** [comment]
> I've done a few tests and `MPI_CXX_DOUBLE_COMPLEX` is recognised by the MPI libraries on ARCHER2.
> Also, running `mpi::internal::typeMPI<std::complex<double>>()` works as expected: it returns `MPI_CXX_DOUBLE_COMPLEX`.

I think MPI_CXX_DOUBLE_COMPLEX might be defined but not supported by the operations. The latest MPICH does not have MPI_CXX_DOUBLE_COMPLEX: https://www.mpich.org/static/docs/v3.4/www3/Constants.html

**Comment by kuangdai** [comment]
I tested on Archer that MPI_C_DOUBLE_COMPLEX and MPI_C_FLOAT_COMPLEX work. Can you please try them on Archer 2?

**Comment by mbareford** [comment]
That is now working!

I assume then that any test program calling MPI_Isend with MPI_CXX_DOUBLE_COMPLEX would also fail. 
Thanks for your help.

**Comment by kuangdai** [comment]
Thank you. I will change the flags to MPI_C_
