### ISSUE TITLE
2 vol models crash, either one of them works of their own.

### ISSUE THREAD

**Issue by wolfjonathan** [kuangdai/AxiSEM-3D#16]
Hi Kuangdai,
I have run into the following issue that I cannot fix: When I use two 3D volumetric models in my simulation at the same time the simulation crashes at time step=2. If I run the same thing but only activate one of them (works for both) the simulation runs as planned. I have played with many parameters without success (e.g. dt, courant number, absorbing boundaries, different meshs...). Volumetric model 1 specifies Vs from a depth of 600km to the CMB and volumetric model 2 specifies Cij in the lowermost mantle (intentionally in this order).
I have attached the output. I would highly appreciate if you could have a look.
Cheers,
Jonathan
[output.txt](https://github.com/kuangdai/AxiSEM-3D/files/6195725/output.txt)

**Comment by kuangdai** [comment]
If SAW642ANb.nc is from 500km to  CMB, why the range of Vs is [0, 7608.51]? No fluid in this domain.

**Comment by wolfjonathan** [comment]
Thank you, Kuangdai. The lowermost depth of the mantle was set to 0 velocity. I have changed that in the input model, but the same thing still happens unfortunately, see output attached.
[output_no_fluid.txt](https://github.com/kuangdai/AxiSEM-3D/files/6204176/output_no_fluid.txt)

**Comment by kuangdai** [comment]
The automatically determined DT is 0.0 in both the output files you sent. The error could be caused by the input files or the code. I need to do some debugging. Please send me the complete input folder.

**Comment by wolfjonathan** [comment]
[small_test.zip](https://github.com/kuangdai/AxiSEM-3D/files/6242187/small_test.zip)
Thank you, Kuangdai. The folder is attached.

**Comment by kuangdai** [comment]
This is caused by a bug in code. Fixed.

Thank you for reporting.

**Comment by wolfjonathan** [comment]
Thanks, Kuangdai. I really appreciate this.
