### ISSUE TITLE
Negative Jacobian

### ISSUE THREAD

**Issue by kuangdai** [kuangdai/AxiSEM-3D#18]
I think there may be a bug in the geometric models. Marjolaine has been unable to get hers to run for several weeks now, and I am trying to run a simulation for Kristiina, and it does not work either. It's always a negative Jacobian error. I suspect it's something to do with coordinate transformations in regional meshes, but I can't say for certain. It is equally possible that I am doing something wrong. But there are two people depending on me to figure this out asap and I am stuck, so I'd be very grateful for your help!

I've been trying to figure out what is happening and I've attached two figures I've created in the process:
The bathymetry_map shows the geometric model. The layer is at 2000m depth and the range is [0 12170]. The circle shows where the mesh should be (source at lat 37.5, lon -16.5, curved mesh with max colatitude 3.2 degrees). I marked data points in red where the bathymetry goes above 2000m, i.e. where the islands are - it should be a safe distance from the mesh.
geometric_gone_wrong is a scatter plot of some data I put out in Quad::setupGLL. This is for the nr=0 slice (nr is set to constant 100, bound by inplane):
x-axis: theta of the GLL points obtained via geodesy::sz2rtheta(getPointSZ(), false)
z-axis: undulation (see below) + r of the GLL points obtained via geodesy::sz2rtheta(getPointSZ(), false)
colormap: undulation of the GLL points at nr=0, obtained via mUndulation->getPointwise()[ipnt](0)
This scatter plot looks very wrong. Do you have any idea what might be the issue?

Thanks a lot!
Claudia

![Bathymetry_map](https://user-images.githubusercontent.com/9271974/113199293-dbf85c00-925e-11eb-9154-2e4242f1bf17.png)
![geometric_gone_wrong](https://user-images.githubusercontent.com/9271974/113199311-e1ee3d00-925e-11eb-9c15-7993a24410c5.png)

**Comment by kuangdai** [comment]
The way you made the second plot is not 100% right because you only used the zeroth order coefficient. 

Please upload the complete input folder.

**Comment by chaindl** [comment]
[input.zip](https://github.com/kuangdai/AxiSEM-3D/files/6240124/input.zip)
Here you go. Thanks Kuangdai!

**Comment by kuangdai** [comment]
1) In `bathy_geo_resampled.nc`, we can see that the shape of `dz` (the undulation data) is 1201x1051, so the data matrix is arranged by `lon x lat` not `lat x lon`, and so the input variable `data_rank` should `[1, 0]` instead of `[0, 1]`. The messy plot you made is likely to be caused by this dimension error. Actually if you run the programme in debug mode, Eigen will abort for size incompatibility. There should not be a bug for calculating spherical coordinates -- this part of code is modularised and used everywhere. If there were an error, the code wouldn't work at all.

2) After changing 1), we still get negative Jacobian, because there's another problem. You are using `depth_below_solid_surface=false`, which means all depth are in reference to the water surface instead of ocean floor. Given that, `min_max: [-1000., 12170.]` does not make too much sense, as it works mostly like `[0, 12170]` (`-1000` is in the air). Because `interface=2000.`, the maximum possible undulation should be 2000, otherwise that interface will rise above the sea. However, the programme shows that the data ranges between `[-4388.67, 3689.65]`. Reducing the undulation by changing `factor` can make it run. 0.7 works.

Please check your data and input.

**Comment by chaindl** [comment]
Thank you for the suggestion with the data ranks - I forgot about that. But depth_below_solid_surface=false is the intended setting. There is an island in the model but it is outside the modeled domain, as shown in the first figure: All areas with dr>=2000 are highlighted in red and the circle shows the region in range of the mesh. So, the problematic areas should not be sampled.

**Comment by kuangdai** [comment]
Because the simulation runs with a slightly smaller undulation, we can infer that one or two elements are distorted because of some large/sharp local undulations. You can try

1) smooth the data (e.g., with 2D Gaussian filter) a little bit, because raw data sampled from ETOPO models are very detailed. 
2) use a higher frequency mesh and a larger Nr  -- the sparser the sampling, the more likely some elements are distorted 


This could not be a code problem. Let us close, please.

**Comment by kuangdai** [comment]
Changing undulation range to `min_max: [-1000., 50000.]` will solve the issue. Some downside undulation is too large and we can make them vary more smoothly by extend the lower bound a little bit.

**Comment by kuangdai** [comment]
The attached figures show the model as seen by AxiSEM3D. Nothing seems wrong. I don't know why you had the vertical bands in your plot.

The negative Jacobian is caused by the fact that, while you wanted to use 2000 m as the interface, the first element layer (surface layer) has a thickness of 2350 m. In other words, the interface cut across the lower part of all surface elements. For a downside undulation, the upper part of these elements will be stretched (in great amount) and the lower part squeezed. Such a sharp change caused an overshooting when the element computes the gradient of undulation and led to negative Jacobian.

The solution is simple: I changed the interface location to 2350 m.  If you want to use 2000 m, make a factious discontinuity there. 



![side](https://user-images.githubusercontent.com/9271974/114081231-353a3e00-98a4-11eb-949c-0ab56aaebcd0.png)
![top](https://user-images.githubusercontent.com/9271974/114081239-37040180-98a4-11eb-88b9-78592c944ffa.png)

**Comment by axelwang** [comment]
Hey @kuangdai ! I tried to plot the GLL points like the first figure you show above, but couldn't find where they are. I looked into the exodus files and found they only contain the geometrical nodes. I am able to plot all the elements since I know all the node coordinates but I couldn't find where are the coordinates stored for the GLL points?
