### ISSUE TITLE
source location failed

### ISSUE THREAD

**Issue by chaindl** [kuangdai/AxiSEM-3D#19]
Hi Kuangdai,

some of the sources in my finite rupture simulations are not found in the mesh and I cannot figure out why. I had the code output the spz coordinates and they seem to be in range. The SE_Model::locateInplane function also considers it in range. In a single-processor test, SE_Model::locateInplane runs until the final "return -1" statement. I'll paste a zip folder of a minimal example which reproduces the error.

Thanks for your help!
Claudia

[input.zip](https://github.com/kuangdai/AxiSEM-3D/files/6823815/input.zip)

**Comment by kuangdai** [comment]
As a single-source problem, you should use SOURCE for geodesy:lat_lon_north_pole_mesh. 

Are you intentionally placing the source off-axis? If yes, put it further away from axis to avoid the axial singularity (numerical error of inverse Newton is greatly amplified in this region).

**Comment by chaindl** [comment]
It's not a single source in the original simulation. The finite rupture consists of 40,000 sources and the input file is several MB. That's why I only included the source that causes the problem in the example.

**Comment by chaindl** [comment]
This is the full source file.

[inparam.source.zip](https://github.com/kuangdai/AxiSEM-3D/files/6881527/inparam.source.zip)

**Comment by kuangdai** [comment]
For now you can manually increase the tolerance used to judge if a point belongs to an element.

Change 

```c++
mQuads[iquad].inverseMapping(sz, xieta)
```

to 
```c++
mQuads[iquad].inverseMapping(sz, xieta, 10, 0.005)
```

There are two such lines: 587, 599 in SE_Model.cpp.


In the long term, maybe we need make this tolerance as an input in advanced.

**Comment by chaindl** [comment]
Ok, it now fails at a later source. I think I can fix this by gradually increasing the tolerance until everything is found. Is there any point in increasing maxIter?

**Comment by chaindl** [comment]
Setting the tolerance to 0.1 fixed it!

**Comment by kuangdai** [comment]
Ignore my previous answer. That is not the right fix.

I believe the real problem is that some of your elements have too skewed shapes, like the one I highlighted in the figure. Inverse mapping ((s,z) to (xi, eta)) on such elements are very unstable or non-unique. The right fix is to make a more isotropic mesh, e.g., by adding some factious discontinuities. 


<img width="521" alt="Screenshot 2021-07-27 at 1 35 14 PM" src="https://user-images.githubusercontent.com/9271974/127154536-3a28cff4-98ea-496b-abc6-8515f770a9f6.png">

**Comment by chaindl** [comment]
I have just reverted the code changes and tried a different mesh and it didn't work. I'll attach the new mesh.

[AxiSEMCartesian_sfba_1.zip](https://github.com/kuangdai/AxiSEM-3D/files/6885710/AxiSEMCartesian_sfba_1.zip)

**Comment by kuangdai** [comment]
Can you  add more discontinuities so that the minimum angle is no less than about 45 degree?

**Comment by chaindl** [comment]
Nope, still no luck...

[AxiSEMCartesian_sfba_plus_1.zip](https://github.com/kuangdai/AxiSEM-3D/files/6886211/AxiSEMCartesian_sfba_plus_1.zip)

**Comment by kuangdai** [comment]
Reason found and fixed.

https://github.com/kuangdai/AxiSEM-3D/commit/d70a67ac3c6545df0ac70fa30895d0e0e06c6ff8
