### ISSUE TITLE
Unable to run 3D input

### ISSUE THREAD

**Issue by wolfjonathan** [kuangdai/AxiSEM-3D#2]
[preloop_diagnosis.log](https://github.com/kuangdai/AxiSEM-3D/files/5423670/preloop_diagnosis.log)
Hi Kuangdai,

3D input gives error message. Seems to be connected to the netcdf input and some parameters that I set or did not set. Can you help with that?

Cheers,
Jonathan

list_of_3D_models:
    #==========================================================================#
    # this key can be arbitrary
    - anijonathan:
        # what: activate this model
        # type: bool
        activated: true
        # what: class name
        # type: string
        # note: current built-in classes include
        #       - StructuredGridV3D: volumetric 3D model on a structured grid
        #       - StructuredGridG3D: geometric 3D model on a structured grid
        #       - StructuredGridO3D: ocean-load 3D model on a structured grid
        #       - Ellipticity: deform the mesh with global ellipticity
        class_name: StructuredGridV3D
        # -------------------------------- #
        # parameters for StructuredGridV3D #
        # -------------------------------- #
        # what: NetCDF data file
        # type: filename
        nc_data_file: prem_br_fe_ppv.nc
        # parameters for grid coordinates
        coordinates:
            # what: type of horizontal coordinates
            # type: string
            # only: DISTANCE_AZIMUTH / XY_CARTESIAN / LATITUDE_LONGITUDE
            horizontal: LATITUDE_LONGITUDE
            # what: type of vertical coordinate
            # type: string
            # only: RADIUS / DEPTH
            vertical: DEPTH
            # what: use solid surface as depth origin
            # type: bool
            # note: used only when vertical = DEPTH
            depth_below_solid_surface: false
            # what: NetCDF variables for the coordinates
            # type: array of string
            nc_variables: [latitude, longitude, depth]
            # what: rank of the coordinates in data
            # type: array of int
            data_rank: [1, 2, 0]
            # what: length unit of the coordinates
            # type: string / value
            # only: km / m / number
            length_unit: km
            # what: angle unit of the coordinates
            # type: string
            # only: degree / radian
            angle_unit: degree
            # what: use undulated (otherwise reference) geometry to
            #       determine the vertical location
            # type: bool
            # note: compatible only with vertical = RADIUS
            undulated_geometry: false
            # what: check inplane model range for the whole element
            # type: bool
            # note: 1) if this parameter is set to true, the element center
            #          will be used to determine whether an element is located
            #          within the "inplane" model range
            #       2) if its center is in range, all its GLL points must be
            #          in range, or an exception will occur; users can extend
            #          the model range slightly to allow for numerical errors
            #       3) this parameter safely realizes inplane discontinuities
            whole_element_inplane: true
        # parameters for properties
        properties:
            - C11:
                # what: NetCDF variable
                nc_var: C11
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C12:
                # what: NetCDF variable
                nc_var: C12
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C13:
                # what: NetCDF variable
                nc_var: C13
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C14:
                # what: NetCDF variable
                nc_var: C14
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C15:
                # what: NetCDF variable
                nc_var: C15
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C16:
                # what: NetCDF variable
                nc_var: C16
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS                
            - C22:
                # what: NetCDF variable
                nc_var: C22
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C23:
                # what: NetCDF variable
                nc_var: C23
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C24:
                # what: NetCDF variable
                nc_var: C24
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C25:
                # what: NetCDF variable
                nc_var: C25
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C26:
                # what: NetCDF variable
                nc_var: C26
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS                
            - C33:
                # what: NetCDF variable
                nc_var: C33
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C34:
                # what: NetCDF variable
                nc_var: C34
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C35:
                # what: NetCDF variable
                nc_var: C35
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C36:
                # what: NetCDF variable
                nc_var: C36
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS      
            - C44:
                # what: NetCDF variable
                nc_var: C44
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C45:
                # what: NetCDF variable
                nc_var: C45
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C46:
                # what: NetCDF variable
                nc_var: C46
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS          
            - C55:
                # what: NetCDF variable
                nc_var: C55
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS
            - C56:
                # what: NetCDF variable
                nc_var: C56
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS                    
            - C66:
                # what: NetCDF variable
                nc_var: C66
                # what: factor or unit
                factor: 1e9
                # what: reference kind
                # only: ABS / REF1D / REF3D / REF_PERTURB
                # note: For any property X:
                #       1) ABS: absolute value
                #          X_3D = value_in_file
                #       2) REF1D: perturbation w.r.t. the 1D reference model
                #          X_3D = (1 + value_in_file) * X_1D
                #       3) REF3D: perturbation w.r.t. the current 3D model
                #          X_3D = (1 + value_in_file) * X_3D
                #       4) REF_PERTURB => perturbation w.r.t. the current
                #                         perturbation or (X_3D - X_1D)
                #          X_3D = (1 + value_in_file) * (X_3D - X_1D) + X_1D
                reference_kind: ABS                    
                
                                
                
            
        # what: store grid data only on the leader processors
        # type: bool
        # note: turn this on if the model is large; set mpi:nproc_per_group
        #       in inparam.advanced.yaml to the number of processors per
        #       node to minimize memory usage
        store_grid_only_on_leaders: true
    #==========================================================================#

**Comment by kuangdai** [comment]
In your model, a parameter coordinates:ellipticity is missing. This does not appear in the Cartesian example because ellipticity is not used in Cartesian. Now I have added this to the input file. 

See https://github.com/kuangdai/AxiSEM-3D/commit/94256098e53af9a5623f43d6013b41c060224ea4

**Comment by wolfjonathan** [comment]
Thanks a lot, Kuangdai. That fixed it!
