### ISSUE TITLE
artefacts from intersections between sf- and domain boundaries

### ISSUE THREAD

**Issue by chaindl** [kuangdai/AxiSEM-3D#21]
Hi Kuangdai!

We have discussed this before and I know you have been working on it. I am just opening this as an official issue to make other users aware of the bug.

There is currently a bug that may cause spurious reflections on solid-fluid boundaries when using multiple processors. They only occur when the sf-boundary coincides with a domain boundary. Since the domain decomposition is different in every simulation, it is random whether the bug is triggered.

**Comment by kuangdai** [comment]
This commit avoids a solid-fluid edge to be partitioned.

https://github.com/kuangdai/AxiSEM-3D/commit/1d1feca45a8c8742e21dd849c7324b44cb3a4225
