### ISSUE TITLE
Apparent issue with a specific point of the mesh

### ISSUE THREAD

**Issue by wolfjonathan** [kuangdai/AxiSEM-3D#3]
<img width="584" alt="Screen Shot 2020-10-27 at 7 31 25 PM" src="https://user-images.githubusercontent.com/73300328/97355524-50d1ff00-1897-11eb-811f-4c6ab4f56b0e.png">

[inparam.model.txt](https://github.com/kuangdai/AxiSEM-3D/files/5447914/inparam.model.txt)
[measured_element_costs.log](https://github.com/kuangdai/AxiSEM-3D/files/5447918/measured_element_costs.log)
[preloop_diagnosis.log](https://github.com/kuangdai/AxiSEM-3D/files/5447919/preloop_diagnosis.log)

Hi Kuangdai,

there is an error, stemming from this line https://github.com/kuangdai/AxiSEM-3D/blob/143b68f14293cf14ea563899b84def00881b656f/SOLVER/src/core/domain/Domain.cpp#L595. This error occurs when I use a dense mesh (e.g. 5s), for example using the default parameters of the mesher for prem_iso. Do you know what the origin of this error might be? Some relevant files are attached, please let me know if you need any further info!

Cheers,

Jonathan

**Comment by kuangdai** [comment]
Can you upload the screen info?  You can do this by

mpirun -np 10 ./axisem3d > screen.txt

Thanks.

**Comment by wolfjonathan** [comment]
[info.log](https://github.com/kuangdai/AxiSEM-3D/files/5448054/info.log)
Sure, I suppose the screen.txt is equivalent to my info.txt, see attached. If not, let me know!

**Comment by kuangdai** [comment]
The log shows that it is stable, isn't? The automatically determined DT is 0.04303 (in the log), while you were using 0.05 in the unstable one.

**Comment by wolfjonathan** [comment]
[info.log](https://github.com/kuangdai/AxiSEM-3D/files/5448096/info.log)
That's the log for the 0.05 simulation, tried different things to solve the issue, also changing dt. AxiSEM3D runs up to a certain point and then stops, independent of dt. This does not happen for all meshes and does not seem to be because of memory.

**Comment by wolfjonathan** [comment]
[new_1D.zip](https://github.com/kuangdai/AxiSEM-3D/files/5448180/new_1D.zip)
Thank you! This is the whole folder including input and all the outputs.

**Comment by wolfjonathan** [comment]
Thank you, Kuangdai:

enforced_dt: NONE 
Courant_number: 0.6

or: 
enforced_dt: 0.025
Courant_number: 0.6

is stable for 1D and 3D simulations.
