### ISSUE TITLE
Archer run issue

### ISSUE THREAD

**Issue by willeaton101** [kuangdai/AxiSEM-3D#5]
Hi Kuangdai, 

I just ran a simulation for a 3390x1000x1000 km cartesian model at 0.5 Hz mesh which had an associated 3D model of file size ~ 2.5 GB. From the log output, axisem managed to produce all the normal output (prior to starting the timeloop) and then crashed at the start of the timesteps. 
Here are the axisem log, archer output and archer error text files. 
[05hzScatter.e7476279.txt](https://github.com/kuangdai/AxiSEM-3D/files/5540692/05hzScatter.e7476279.txt)
[05hzScatter.o7476279.txt](https://github.com/kuangdai/AxiSEM-3D/files/5540693/05hzScatter.o7476279.txt)
[output_axisem3d_05Hz.txt](https://github.com/kuangdai/AxiSEM-3D/files/5540694/output_axisem3d_05Hz.txt)

I have emailed a tar file containing all input parameters/3D models as theyre too large to attach uncompressed and it wont support a tar file upload on here. 

Best wishes,
Will

**Comment by kuangdai** [comment]
You are using a large buffer size (1000) for wavefield output. 

Use either a small buffer size or run it on more nodes.

**Comment by willeaton101** [comment]
Thanks, all sorted.
